"""mapped organization_id to all models

Revision ID: a7b892c8d632
Revises: b5d08fade71a
Create Date: 2026-08-01 14:27:33.801554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7b892c8d632'
down_revision: Union[str, Sequence[str], None] = 'b5d08fade71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE audit_events SET tenant_id = 'tenant-1' WHERE tenant_id = 'unknown';")
    op.execute("UPDATE enterprise_audit_logs SET tenant_id = 'tenant-1' WHERE tenant_id = 'unknown';")
    op.execute("UPDATE notification_templates SET tenant_id = '__platform__' WHERE tenant_id = '**platform**';")
    op.execute("UPDATE notification_templates SET tenant_id = 'tenant-1' WHERE tenant_id = 'current_user.tenant_id';")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_state_records', 'agent_type',
               existing_type=sa.VARCHAR(length=50),
               comment='AITask value for this agent.',
               existing_comment='AITask string value for this agent.',
               existing_nullable=False)
    op.alter_column('agent_state_records', 'last_error',
               existing_type=sa.VARCHAR(length=500),
               comment='Safe error summary only — no stack traces or secrets.',
               existing_comment='Safe error summary — no stack traces or secrets.',
               existing_nullable=True)
    op.create_index(op.f('ix_agent_state_records_id'), 'agent_state_records', ['id'], unique=False)
    op.create_index(op.f('ix_agent_state_records_tenant_id'), 'agent_state_records', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'agent_state_records', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'ai_brand_safety_rules', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'ai_guardrail_violations', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('assignment_overrides', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.drop_index(op.f('idx_assignment_overrides_job_id'), table_name='assignment_overrides')
    op.create_index(op.f('ix_assignment_overrides_tenant_id'), 'assignment_overrides', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'assignment_overrides', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('idx_audit_events_tech_id'), table_name='audit_events')
    op.create_foreign_key(None, 'audit_events', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.add_column(
    'communication_channel_configurations',
    sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_communication_channel_configurations_tenant_id'), 'communication_channel_configurations', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'communication_channel_configurations', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('communication_configuration_audits', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_communication_configuration_audits_tenant_id'), 'communication_configuration_audits', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'communication_configuration_audits', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'customer_preference_audits', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('customer_profiles_extended_user_id_key'), 'customer_profiles_extended', type_='unique')
    op.create_index(op.f('ix_customer_profiles_extended_tenant_id'), 'customer_profiles_extended', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_customer_profiles_extended_user_id'), 'customer_profiles_extended', ['user_id'], unique=True)
    op.create_foreign_key(None, 'customer_profiles_extended', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('dispatcher_alerts', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_dispatcher_alerts_tenant_id'), 'dispatcher_alerts', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'dispatcher_alerts', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('idx_dispatcher_notifications_tech_id'), table_name='dispatcher_notifications')
    op.create_index(op.f('ix_enterprise_audit_logs_action'), 'enterprise_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_enterprise_audit_logs_correlation_id'), 'enterprise_audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_enterprise_audit_logs_entity_id'), 'enterprise_audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_enterprise_audit_logs_entity_type'), 'enterprise_audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_enterprise_audit_logs_role'), 'enterprise_audit_logs', ['role'], unique=False)
    op.create_index(op.f('ix_enterprise_audit_logs_tenant_id'), 'enterprise_audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_enterprise_audit_logs_timestamp'), 'enterprise_audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_enterprise_audit_logs_user_id'), 'enterprise_audit_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'enterprise_audit_logs', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'eta_history', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'gps_purge_audit_logs', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('gps_rejected_ping_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'gps_rejected_ping_logs', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('job_assignments', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_job_assignments_tenant_id'), 'job_assignments', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'job_assignments', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('job_closures', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_job_closures_tenant_id'), 'job_closures', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('job_closures_job_id_fkey'), 'job_closures', type_='foreignkey')
    op.create_foreign_key(None, 'job_closures', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'job_closures', 'jobs', ['job_id'], ['id'])
    op.drop_column('job_closures', 'technician_id')
    op.create_foreign_key(None, 'jobs', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('notification_deliveries', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.execute("""
            ALTER TABLE notification_deliveries
            ALTER COLUMN job_id TYPE INTEGER
            USING job_id::integer;
            """)
    op.drop_index(op.f('ix_notification_deliveries_tech_id'), table_name='notification_deliveries')
    op.create_index(op.f('ix_notification_deliveries_tenant_id'), 'notification_deliveries', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'notification_deliveries', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'notification_deliveries', 'technicians', ['tech_id'], ['tech_id'])
    op.create_foreign_key(None, 'notification_deliveries', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'notification_templates', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('uq_organizations_slug'), 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('ix_organizations_status'), 'organizations', ['status'], unique=False)
    op.create_index(op.f('ix_override_audit_events_tenant_id'), 'override_audit_events', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'override_audit_events', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('preference_audit_logs', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_preference_audit_logs_tenant_id'), 'preference_audit_logs', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'preference_audit_logs', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('idx_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.add_column('scoring_configurations', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_scoring_configurations_id'), 'scoring_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_scoring_configurations_tenant_id'), 'scoring_configurations', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'scoring_configurations', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('security_audit_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'security_audit_logs', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('service_requests_request_number_key'), 'service_requests', type_='unique')
    op.create_index(op.f('ix_service_requests_customer_user_id'), 'service_requests', ['customer_user_id'], unique=False)
    op.create_index(op.f('ix_service_requests_linked_job_id'), 'service_requests', ['linked_job_id'], unique=False)
    op.create_index(op.f('ix_service_requests_request_number'), 'service_requests', ['request_number'], unique=True)
    op.create_index(op.f('ix_service_requests_tenant_id'), 'service_requests', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'service_requests', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.execute("ALTER TABLE sla_escalations ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50);")
    op.execute("UPDATE sla_escalations SET tenant_id = 'tenant-1' WHERE tenant_id IS NULL;")
    op.create_index(op.f('ix_sla_escalations_tenant_id'), 'sla_escalations', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'sla_escalations', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('technician_profiles_user_id_key'), 'technician_profiles', type_='unique')
    op.create_index(op.f('ix_technician_profiles_tenant_id'), 'technician_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_technician_profiles_user_id'), 'technician_profiles', ['user_id'], unique=True)
    op.create_foreign_key(None, 'technician_profiles', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'technicians', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_tenant_gps_configurations_tenant_id'), table_name='tenant_gps_configurations')
    op.create_foreign_key(None, 'tenant_gps_configurations', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('tenants', sa.Column('parent_tenant_id', sa.String(length=50), nullable=True))
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_foreign_key(None, 'tenants', 'tenants', ['parent_tenant_id'], ['id'])
    op.drop_column('tenants', 'created_at')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_index(op.f('idx_users_tenant_id'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('idx_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.add_column('tenants', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('tenants', 'parent_tenant_id')
    op.drop_constraint(None, 'tenant_gps_configurations', type_='foreignkey')
    op.create_index(op.f('ix_tenant_gps_configurations_tenant_id'), 'tenant_gps_configurations', ['tenant_id'], unique=False)
    op.drop_constraint(None, 'technicians', type_='foreignkey')
    op.drop_constraint(None, 'technician_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_technician_profiles_user_id'), table_name='technician_profiles')
    op.drop_index(op.f('ix_technician_profiles_tenant_id'), table_name='technician_profiles')
    op.create_unique_constraint(op.f('technician_profiles_user_id_key'), 'technician_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'sla_escalations', type_='foreignkey')
    op.drop_index(op.f('ix_sla_escalations_tenant_id'), table_name='sla_escalations')
    op.drop_column('sla_escalations', 'tenant_id')
    op.drop_constraint(None, 'service_requests', type_='foreignkey')
    op.drop_index(op.f('ix_service_requests_tenant_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_request_number'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_linked_job_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_customer_user_id'), table_name='service_requests')
    op.create_unique_constraint(op.f('service_requests_request_number_key'), 'service_requests', ['request_number'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'security_audit_logs', type_='foreignkey')
    op.alter_column('security_audit_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'scoring_configurations', type_='foreignkey')
    op.drop_index(op.f('ix_scoring_configurations_tenant_id'), table_name='scoring_configurations')
    op.drop_index(op.f('ix_scoring_configurations_id'), table_name='scoring_configurations')
    op.drop_column('scoring_configurations', 'id')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.create_index(op.f('idx_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_constraint(None, 'preference_audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_preference_audit_logs_tenant_id'), table_name='preference_audit_logs')
    op.drop_column('preference_audit_logs', 'tenant_id')
    op.drop_constraint(None, 'override_audit_events', type_='foreignkey')
    op.drop_index(op.f('ix_override_audit_events_tenant_id'), table_name='override_audit_events')
    op.drop_index(op.f('ix_organizations_status'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_unique_constraint(op.f('uq_organizations_slug'), 'organizations', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'notification_templates', type_='foreignkey')
    op.drop_constraint(None, 'notification_deliveries', type_='foreignkey')
    op.drop_constraint(None, 'notification_deliveries', type_='foreignkey')
    op.drop_constraint(None, 'notification_deliveries', type_='foreignkey')
    op.drop_index(op.f('ix_notification_deliveries_tenant_id'), table_name='notification_deliveries')
    op.create_index(op.f('ix_notification_deliveries_tech_id'), 'notification_deliveries', ['tech_id'], unique=False)
    op.alter_column(
        'notification_deliveries',
        'job_id',
        existing_type=sa.VARCHAR(length=36),
        type_=sa.Integer(),
        postgresql_using="job_id::integer",
        existing_nullable=False
    )
    op.drop_column('notification_deliveries', 'tenant_id')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.add_column('job_closures', sa.Column('technician_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'job_closures', type_='foreignkey')
    op.drop_constraint(None, 'job_closures', type_='foreignkey')
    op.create_foreign_key(op.f('job_closures_job_id_fkey'), 'job_closures', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_job_closures_tenant_id'), table_name='job_closures')
    op.drop_column('job_closures', 'tenant_id')
    op.drop_constraint(None, 'job_assignments', type_='foreignkey')
    op.drop_index(op.f('ix_job_assignments_tenant_id'), table_name='job_assignments')
    op.drop_column('job_assignments', 'tenant_id')
    op.drop_constraint(None, 'gps_rejected_ping_logs', type_='foreignkey')
    op.alter_column('gps_rejected_ping_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'gps_purge_audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'eta_history', type_='foreignkey')
    op.drop_constraint(None, 'eta_history', type_='foreignkey')
    op.drop_constraint(None, 'enterprise_audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_enterprise_audit_logs_user_id'), table_name='enterprise_audit_logs')
    op.drop_index(op.f('ix_enterprise_audit_logs_timestamp'), table_name='enterprise_audit_logs')
    op.drop_index(op.f('ix_enterprise_audit_logs_tenant_id'), table_name='enterprise_audit_logs')
    op.drop_index(op.f('ix_enterprise_audit_logs_role'), table_name='enterprise_audit_logs')
    op.drop_index(op.f('ix_enterprise_audit_logs_entity_type'), table_name='enterprise_audit_logs')
    op.drop_index(op.f('ix_enterprise_audit_logs_entity_id'), table_name='enterprise_audit_logs')
    op.drop_index(op.f('ix_enterprise_audit_logs_correlation_id'), table_name='enterprise_audit_logs')
    op.drop_index(op.f('ix_enterprise_audit_logs_action'), table_name='enterprise_audit_logs')
    op.create_index(op.f('idx_dispatcher_notifications_tech_id'), 'dispatcher_notifications', ['tech_id'], unique=False)
    op.drop_constraint(None, 'dispatcher_alerts', type_='foreignkey')
    op.drop_index(op.f('ix_dispatcher_alerts_tenant_id'), table_name='dispatcher_alerts')
    op.drop_column('dispatcher_alerts', 'tenant_id')
    op.drop_constraint(None, 'customer_profiles_extended', type_='foreignkey')
    op.drop_index(op.f('ix_customer_profiles_extended_user_id'), table_name='customer_profiles_extended')
    op.drop_index(op.f('ix_customer_profiles_extended_tenant_id'), table_name='customer_profiles_extended')
    op.create_unique_constraint(op.f('customer_profiles_extended_user_id_key'), 'customer_profiles_extended', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'customer_preference_audits', type_='foreignkey')
    op.drop_constraint(None, 'communication_configuration_audits', type_='foreignkey')
    op.drop_index(op.f('ix_communication_configuration_audits_tenant_id'), table_name='communication_configuration_audits')
    op.drop_column('communication_configuration_audits', 'tenant_id')
    op.drop_constraint(None, 'communication_channel_configurations', type_='foreignkey')
    op.drop_index(op.f('ix_communication_channel_configurations_tenant_id'), table_name='communication_channel_configurations')
    op.drop_column('communication_channel_configurations', 'tenant_id')
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    op.create_index(op.f('idx_audit_events_tech_id'), 'audit_events', ['tech_id'], unique=False)
    op.drop_constraint(None, 'assignment_overrides', type_='foreignkey')
    op.drop_index(op.f('ix_assignment_overrides_tenant_id'), table_name='assignment_overrides')
    op.create_index(op.f('idx_assignment_overrides_job_id'), 'assignment_overrides', ['job_id'], unique=False)
    op.drop_column('assignment_overrides', 'tenant_id')
    op.drop_constraint(None, 'ai_guardrail_violations', type_='foreignkey')
    op.drop_constraint(None, 'ai_brand_safety_rules', type_='foreignkey')
    op.drop_constraint(None, 'agent_state_records', type_='foreignkey')
    op.drop_index(op.f('ix_agent_state_records_tenant_id'), table_name='agent_state_records')
    op.drop_index(op.f('ix_agent_state_records_id'), table_name='agent_state_records')
    op.alter_column('agent_state_records', 'last_error',
               existing_type=sa.VARCHAR(length=500),
               comment='Safe error summary — no stack traces or secrets.',
               existing_comment='Safe error summary only — no stack traces or secrets.',
               existing_nullable=True)
    op.alter_column('agent_state_records', 'agent_type',
               existing_type=sa.VARCHAR(length=50),
               comment='AITask string value for this agent.',
               existing_comment='AITask value for this agent.',
               existing_nullable=False)
    # ### end Alembic commands ###
